"""creating refundedTicket relation

Revision ID: 427a33fa79c4
Revises: f797dbb2844d
Create Date: 2024-11-29 04:08:28.142410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427a33fa79c4'
down_revision: Union[str, None] = 'f797dbb2844d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
