"""booked ticket, feedback column addition

Revision ID: 6f5e6b27045c
Revises: a6abfa256563
Create Date: 2024-11-28 09:09:12.509708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f5e6b27045c'
down_revision: Union[str, None] = 'a6abfa256563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booked_tickets', sa.Column('feed_back_description', sa.String(), nullable=True))
    op.create_index(op.f('ix_booked_tickets_feed_back_description'), 'booked_tickets', ['feed_back_description'], unique=False)
    op.add_column('route_tickets', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'route_tickets', 'transport_companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route_tickets', type_='foreignkey')
    op.drop_column('route_tickets', 'company_id')
    op.drop_index(op.f('ix_booked_tickets_feed_back_description'), table_name='booked_tickets')
    op.drop_column('booked_tickets', 'feed_back_description')
    # ### end Alembic commands ###
